### ISSUE TITLE
memory issue when signing large documents

### ISSUE THREAD

**Issue by zmousm** [leifj/pyXMLSecurity#25]
When pyFF signs a large XML document, for example the complete eduGAIN aggregate, some times python may abort with a `MemoryError` exception, especially on a memory stressed system. This may be due to the fact that `unescape_xml_entities()` in `xmlsec.utils` runs a regular expression against the whole document.

```python
Traceback (most recent call last):
  File "/opt/pyff/lib/python2.7/site-packages/pyff/md.py", line 71, in main
    plumbing(p).process(md, state={'batch': True, 'stats': {}})
  File "/opt/pyff/lib/python2.7/site-packages/pyff/pipes.py", line 236, in process
    return Plumbing.Request(self, md, t, state=state).process(self)
  File "/opt/pyff/lib/python2.7/site-packages/pyff/pipes.py", line 215, in process
    ot = cb(self, *opts)
  File "/opt/pyff/lib/python2.7/site-packages/pyff/builtins.py", line 149, in fork
    ip._process(ireq)
  File "/opt/pyff/lib/python2.7/site-packages/pyff/pipes.py", line 254, in _process
    ot = pipe(req, *opts)
  File "/opt/pyff/lib/python2.7/site-packages/pyff/builtins.py", line 149, in fork
    ip._process(ireq)
  File "/opt/pyff/lib/python2.7/site-packages/pyff/pipes.py", line 254, in _process
    ot = pipe(req, *opts)
  File "/opt/pyff/lib/python2.7/site-packages/pyff/builtins.py", line 766, in sign
    xmlsec.sign(req.t, key_file, cert_file, **opts)
  File "/opt/pyff/lib/python2.7/site-packages/xmlsec/__init__.py", line 405, in sign
    _process_references(t, sig, return_verified=False, sig_path=sig_path)
  File "/opt/pyff/lib/python2.7/site-packages/xmlsec/__init__.py", line 172, in _process_references
    obj = _transform(_alg(tr), obj, tr=tr, sig_path=sig_path)
  File "/opt/pyff/lib/python2.7/site-packages/xmlsec/__init__.py", line 250, in _transform
    return _c14n(t, exclusive=True, with_comments=True, inclusive_prefix_list=nslist, schema=schema)
  File "/opt/pyff/lib/python2.7/site-packages/xmlsec/__init__.py", line 232, in _c14n
    u = unescape_xml_entities(buf.decode("utf8", 'strict')).encode("utf8").strip()
  File "/opt/pyff/lib/python2.7/site-packages/xmlsec/utils.py", line 76, in unescape_xml_entities
    return re.compile("&#?\w+;").sub(fixup, text)
MemoryError
ERROR:root:
```

Would it make sense to somehow split `text` in chunks (when `len(text)` exceeds some arbitrary threshold) and iterate over them instead of running `re.sub()` on the whole document?

**Comment by leifj** [comment]
Thats an interesting idea - certainly worth exploring for speed reasons but do you have any measurements to support the theory that this is where memory is consumed?

**Comment by leifj** [comment]
... note that even though this is where the exception occurs, it could just be where the camels back got broken

**Comment by zmousm** [comment]
That could also be the case. This runs as part of a pyFF pipeline with many forks, which output signed feeds. When I run `xmlsign` directly on this document, I can't seem to trigger a `MemoryError`. I will try to do some memory profiling and come back with some data.

**Comment by leifj** [comment]
I actually did memory profiling on the function and it does copy the input buffer which doubles the size of any buffer-allocation. This could be an issue...

**Comment by zmousm** [comment]
Well, the particular function adds to the memory footprint almost as much as the size of the string argument, as expected. I somehow thought iteration would help with the replacement function, but it won't.

Memory usage seems to be mostly affected by the use of pyFF fork pipes, which do `deepcopy()`. The memory from each copy is not returned, which is also somewhat expected but that is another story.

The way this works, I don't see room for improvement here, do you?

**Comment by leifj** [comment]
I'm playing with some ideas... I haven't given up yet.

**Comment by leifj** [comment]
can you run some tests using HEAD now?

**Comment by zmousm** [comment]
I pulled a75fdd063cb70e959efa977676f00999c33992a9 but I don't see anything different. Should I?

**Comment by leifj** [comment]
yeah absolutely - it disables the whole entityref normalization call

**Comment by zmousm** [comment]
Sorry for the silence. I had not actually pulled that commit after all.

I do see now that `unescape_xml_entities()` is never called, so you let lxml handle this while also encoding entity refs to utf-8. Right?

There is an apparent positive effect on overall memory usage: I see pyFF using up to 750 MB for the same pipeline and input that would previously use up to 950 MB of memory.

**Comment by leifj** [comment]
Skickat från min iPhone

> 4 apr. 2016 kl. 04:57 skrev Zenon Mousmoulas <notifications@github.com>:
> 
> Sorry for the silence. I had not actually pulled that commit after all.
> 
> I do see now that unescape_xml_entities() is never called, so you let lxml handle this while also encoding entity refs to utf-8. Right?
> 

Right
> There is an apparent positive effect on overall memory usage: I see pyFF using up to 750 MB for the same pipeline and input that would previously use up to 950 MB of memory.
> 
Ah nice!

Nothing broke for you?

**Comment by zmousm** [comment]
On 4 April 2016 at 14:56, Leif Johansson <notifications@github.com> wrote:

>
> > 4 apr. 2016 kl. 04:57 skrev Zenon Mousmoulas <notifications@github.com>:
> >
> > Sorry for the silence. I had not actually pulled that commit after all.
> >
> > I do see now that unescape_xml_entities() is never called, so you let
> lxml handle this while also encoding entity refs to utf-8. Right?
> >
>
> Right
> > There is an apparent positive effect on overall memory usage: I see pyFF
> using up to 750 MB for the same pipeline and input that would previously
> use up to 950 MB of memory.
> >
> Ah nice!
>
> Nothing broke for you?
>

Not that I could see. But let me check again (with a particular test
document that includes character refs) and get back to you.

**Comment by zmousm** [comment]
Again, sorry for the delay.

I tested with some documents that include char refs (such as `&#13;`), no problems with that either (validation and signing). I see the entity refs are preserved in the output, which is good.

So it's apparently all good :+1: Go ahead and close this if you want.

**Comment by leifj** [comment]
ok - closing
