### ISSUE TITLE
how to sign with exclusive c14n?

### ISSUE THREAD

**Issue by rhoerbe** [leifj/pyXMLSecurity#27]
What needs to be done to create signatures using http://www.w3.org/2001/10/xml-exc-c14n#

**Comment by leifj** [comment]
checkout the documentation for xmlsec.Config: https://github.com/leifj/pyXMLSecurity/blob/master/src/xmlsec/__init__.py#L25

**Comment by rhoerbe** [comment]
OK. However, exc c14n should be default as well:
[SAML-Meta]: 3.1.4 Transforms 
Signatures in SAML metadata SHOULD NOT contain transforms other than the enveloped signature
 transform .. or the exclusive canonicalization transforms. 
Verifiers of signatures MAY reject signatures that contain other transform algorithms as invalid.

**Comment by leifj** [comment]
Thats a good point. I'll open a separate issue

**Comment by rhoerbe** [comment]
I did not find the issue that is replacing this one, so I am reporting here instead.
When verifying a signature with signxml, it reported a digest error, which was not reported by xmlsectool. The maintainer claims that this is due to a bug in handling inclusinve c14n in pyxmlsec:
https://github.com/kislyuk/signxml/issues/41#issuecomment-231601209
This should go away when using exclusive c14n, of course.

**Comment by leifj** [comment]
Skickat från min iPhone

> 10 juli 2016 kl. 19:51 skrev Rainer Hörbe <notifications@github.com>:
> 
> I did not find the issue that is replacing this one, so I am reporting here instead.
> When verifying a signature with signxml, it reported a digest error, which was not reported by xmlsectool. The maintainer claims that this is due to a bug in handling inclusinve c14n in pyxmlsec:
> kislyuk/signxml#41 (comment)
> This should go away when using exclusive c14n, of course.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Can you include a (small) bit of sample xml demonstrating the issue?
