### ISSUE TITLE
SAML test cases are not valid XML

### ISSUE THREAD

**Issue by jethrogb** [leifj/pyXMLSecurity#37]
The test cases in [src/xmlsec/test/data/signverify/SAML_assertion1](https://github.com/leifj/pyXMLSecurity/tree/master/src/xmlsec/test/data/signverify/SAML_assertion1) and [src/xmlsec/test/data/signverify/SAML_assertion_sha256](https://github.com/leifj/pyXMLSecurity/tree/master/src/xmlsec/test/data/signverify/SAML_assertion_sha256) uses an `ID` value that is entirely numeric. XML IDs must not start with a number: https://www.w3.org/TR/REC-xml/#sec-attribute-types https://www.w3.org/TR/REC-xml/#NT-Name

**Comment by leifj** [comment]
You're talking about the Id="Signature1" attribute right?

**Comment by jethrogb** [comment]
Thanks!
